---
# - name: Install Homebrew
#   ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#   args:
#     creates: /usr/local/bin/brew

- name: Update Homebrew
  ansible.builtin.command: /opt/homebrew/bin/brew update

- name: Install Jenkins
  community.general.homebrew_cask:
    name: "{{ jenkins_homebrew_package }}"
    state: present

- name: Ensure Jenkins service is started
  ansible.builtin.command: /opt/homebrew/bin/brew services start "{{ jenkins_service_name }}"

- name: Wait for Jenkins to start
  wait_for:
    host: localhost
    port: "{{ jenkins_port }}"
    state: started
    timeout: 60
